### ISSUE TITLE
Score "(null)"

### ISSUE THREAD

**Issue by palrogg** [l800891/Sakura-Fly#3]
Great, funny little game!

Two details:
- when your score is zero, it displays "(null)"
- at the very beginning, for new players, vertical bars come really fast (maybe it could be more progressive for the first ones)

![img_0309](https://cloud.githubusercontent.com/assets/12730304/17638735/39c64a12-60ba-11e6-841a-1d33ef1cfb20.PNG)

Edit: add screenshot

**Comment by l800891** [comment]
Good catch! will fix that.
For the level thing it is easy to implement but not my original idea. Although the speed stays the same, the difficulty level increases as the score goes up because it requires focus, and focus for a long time is hard.  Regarding the progressive approach, a good player may get inpatient at last because it is so easy in the beginning and may take too much additional time to break their record.
